language: node_js
node_js:
- '6'
before_script:
- npm install -g less
script: "./build.sh"
deploy:
  provider: s3
  access_key_id: AKIAJZMBZYLHJEGLJL5A
  secret_access_key:
    secure: cAX/MdNt926ZyMvwiHEiU0LBWHxiTr6O3Y/WW96iVluCmZpifOl+ZzMpTTmc6qDAQ6dPbk8MCYMl+MdESybpeTDQb/fgBh9j6DW28D+hPI1U/V23jrVx67SUPN3GyIQMxiCOfKymx2Bw1m05D34SGFr5wjhekvidajCwMc6AuUUo7WK4vFkeZSWOtqYs4/cAjhhAR11uqd48UWiI/HHrqgG0XDUES97tUJwuEEfrEAa2KJoyA34+HGQdT2gu4fqE73/lCg428qZSoqAmI/BugKI8lKXOjHg3WqDuvgkiTlpsm42551hRnQqAIXrdhPn75WUdfWWu04qy33cLSSxJLtsNGf3ZVYsVArDOk6t2os3qDV63g7HxvVwfOLLMwmb+rpbKp4OB8ku4Hrt5pzn7khT5ueADfNsLtckDkKIsqcW6nnjliT6Jc3eagCy2Bx/aXIjxJCQUisRzEowoN0aYovvxTYu7umHdiKq/eweNFh3+zOFqaT52rZlEnIXH0OSQqxIokVc9+cCUfEf+eSYRJNI+Zr3ybNM0bcj0Kf8RdnfN5nFYwYnWtBqb0MAYbf17kOoZ20VERxob/0rjWTknVjLA3kAwRXLKwp29emYVPJ6y9gXZa5PJsxCue4bQlgrn5AY6iZXz4m2OxJl9Iql41cjZZF5l/2HXxuPFV7QetVw=
  bucket: S3 Bucket
  skip_cleanup: true
  acl: public_read
